<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('countries')->delete();

        $countries = [
            ['code' => 'US', 'flag' => 'US.png', 'name' => 'United States'],
            ['code' => 'CA', 'flag' => 'CA.png', 'name' => 'Canada'],
            ['code' => 'AF', 'flag' => 'AF.png', 'name' => 'Afghanistan'],
            ['code' => 'AL', 'flag' => 'AL.png', 'name' => 'Albania'],
            ['code' => 'DZ', 'flag' => 'DZ.png', 'name' => 'Algeria'],
            ['code' => 'AS', 'flag' => 'AS.png', 'name' => 'American Samoa'],
            ['code' => 'AD', 'flag' => 'AD.png', 'name' => 'Andorra'],
            ['code' => 'AO', 'flag' => 'AO.png', 'name' => 'Angola'],
            ['code' => 'AI', 'flag' => 'AI.png', 'name' => 'Anguilla'],
            ['code' => 'AQ', 'flag' => 'AQ.png', 'name' => 'Antarctica'],
            ['code' => 'AG', 'flag' => 'AG.png', 'name' => 'Antigua and/or Barbuda'],
            ['code' => 'AR', 'flag' => 'AR.png', 'name' => 'Argentina'],
            ['code' => 'AM', 'flag' => 'AM.png', 'name' => 'Armenia'],
            ['code' => 'AW', 'flag' => 'AW.png', 'name' => 'Aruba'],
            ['code' => 'AU', 'flag' => 'AU.png', 'name' => 'Australia'],
            ['code' => 'AT', 'flag' => 'AT.png', 'name' => 'Austria'],
            ['code' => 'AZ', 'flag' => 'AZ.png', 'name' => 'Azerbaijan'],
            ['code' => 'BS', 'flag' => 'BS.png', 'name' => 'Bahamas'],
            ['code' => 'BH', 'flag' => 'BH.png', 'name' => 'Bahrain'],
            ['code' => 'BD', 'flag' => 'BD.png', 'name' => 'Bangladesh'],
            ['code' => 'BB', 'flag' => 'BB.png', 'name' => 'Barbados'],
            ['code' => 'BY', 'flag' => 'BY.png', 'name' => 'Belarus'],
            ['code' => 'BE', 'flag' => 'BE.png', 'name' => 'Belgium'],
            ['code' => 'BZ', 'flag' => 'BZ.png', 'name' => 'Belize'],
            ['code' => 'BJ', 'flag' => 'BJ.png', 'name' => 'Benin'],
            ['code' => 'BM', 'flag' => 'BM.png', 'name' => 'Bermuda'],
            ['code' => 'BT', 'flag' => 'BT.png', 'name' => 'Bhutan'],
            ['code' => 'BO', 'flag' => 'BO.png', 'name' => 'Bolivia'],
            ['code' => 'BA', 'flag' => 'BA.png', 'name' => 'Bosnia and Herzegovina'],
            ['code' => 'BW', 'flag' => 'BW.png', 'name' => 'Botswana'],
            ['code' => 'BV', 'flag' => 'BV.png', 'name' => 'Bouvet Island'],
            ['code' => 'BR', 'flag' => 'BR.png', 'name' => 'Brazil'],
            ['code' => 'IO', 'flag' => 'IO.png', 'name' => 'British lndian Ocean Territory'],
            ['code' => 'BN', 'flag' => 'BN.png', 'name' => 'Brunei Darussalam'],
            ['code' => 'BG', 'flag' => 'BG.png', 'name' => 'Bulgaria'],
            ['code' => 'BF', 'flag' => 'BF.png', 'name' => 'Burkina Faso'],
            ['code' => 'BI', 'flag' => 'BI.png', 'name' => 'Burundi'],
            ['code' => 'KH', 'flag' => 'KH.png', 'name' => 'Cambodia'],
            ['code' => 'CM', 'flag' => 'CM.png', 'name' => 'Cameroon'],
            ['code' => 'CV', 'flag' => 'CV.png', 'name' => 'Cape Verde'],
            ['code' => 'KY', 'flag' => 'KY.png', 'name' => 'Cayman Islands'],
            ['code' => 'CF', 'flag' => 'CF.png', 'name' => 'Central African Republic'],
            ['code' => 'TD', 'flag' => 'TD.png', 'name' => 'Chad'],
            ['code' => 'CL', 'flag' => 'CL.png', 'name' => 'Chile'],
            ['code' => 'CN', 'flag' => 'CN.png', 'name' => 'China'],
            ['code' => 'CX', 'flag' => 'CX.png', 'name' => 'Christmas Island'],
            ['code' => 'CC', 'flag' => 'CC.png', 'name' => 'Cocos (Keeling) Islands'],
            ['code' => 'CO', 'flag' => 'CO.png', 'name' => 'Colombia'],
            ['code' => 'KM', 'flag' => 'KM.png', 'name' => 'Comoros'],
            ['code' => 'CG', 'flag' => 'CG.png', 'name' => 'Congo'],
            ['code' => 'CK', 'flag' => 'CK.png', 'name' => 'Cook Islands'],
            ['code' => 'CR', 'flag' => 'CR.png', 'name' => 'Costa Rica'],
            ['code' => 'HR', 'flag' => 'HR.png', 'name' => 'Croatia (Hrvatska)'],
            ['code' => 'CU', 'flag' => 'CU.png', 'name' => 'Cuba'],
            ['code' => 'CY', 'flag' => 'CY.png', 'name' => 'Cyprus'],
            ['code' => 'CZ', 'flag' => 'CZ.png', 'name' => 'Czech Republic'],
            ['code' => 'CD', 'flag' => 'CD.png', 'name' => 'Democratic Republic of Congo'],
            ['code' => 'DK', 'flag' => 'DK.png', 'name' => 'Denmark'],
            ['code' => 'DJ', 'flag' => 'DJ.png', 'name' => 'Djibouti'],
            ['code' => 'DM', 'flag' => 'DM.png', 'name' => 'Dominica'],
            ['code' => 'DO', 'flag' => 'DO.png', 'name' => 'Dominican Republic'],
            ['code' => 'TP', 'flag' => 'TP.png', 'name' => 'East Timor'],
            ['code' => 'EC', 'flag' => 'EC.png', 'name' => 'Ecudaor'],
            ['code' => 'EG', 'flag' => 'EG.png', 'name' => 'Egypt'],
            ['code' => 'SV', 'flag' => 'SV.png', 'name' => 'El Salvador'],
            ['code' => 'GQ', 'flag' => 'GQ.png', 'name' => 'Equatorial Guinea'],
            ['code' => 'ER', 'flag' => 'ER.png', 'name' => 'Eritrea'],
            ['code' => 'EE', 'flag' => 'EE.png', 'name' => 'Estonia'],
            ['code' => 'ET', 'flag' => 'ET.png', 'name' => 'Ethiopia'],
            ['code' => 'FK', 'flag' => 'FK.png', 'name' => 'Falkland Islands (Malvinas)'],
            ['code' => 'FO', 'flag' => 'FO.png', 'name' => 'Faroe Islands'],
            ['code' => 'FJ', 'flag' => 'FJ.png', 'name' => 'Fiji'],
            ['code' => 'FI', 'flag' => 'FI.png', 'name' => 'Finland'],
            ['code' => 'FR', 'flag' => 'FR.png', 'name' => 'France'],
            ['code' => 'FX', 'flag' => 'FX.png', 'name' => 'France, Metropolitan'],
            ['code' => 'GF', 'flag' => 'GF.png', 'name' => 'French Guiana'],
            ['code' => 'PF', 'flag' => 'PF.png', 'name' => 'French Polynesia'],
            ['code' => 'TF', 'flag' => 'TF.png', 'name' => 'French Southern Territories'],
            ['code' => 'GA', 'flag' => 'GA.png', 'name' => 'Gabon'],
            ['code' => 'GM', 'flag' => 'GM.png', 'name' => 'Gambia'],
            ['code' => 'GE', 'flag' => 'GE.png', 'name' => 'Georgia'],
            ['code' => 'DE', 'flag' => 'DE.png', 'name' => 'Germany'],
            ['code' => 'GH', 'flag' => 'GH.png', 'name' => 'Ghana'],
            ['code' => 'GI', 'flag' => 'GI.png', 'name' => 'Gibraltar'],
            ['code' => 'GR', 'flag' => 'GR.png', 'name' => 'Greece'],
            ['code' => 'GL', 'flag' => 'GL.png', 'name' => 'Greenland'],
            ['code' => 'GD', 'flag' => 'GD.png', 'name' => 'Grenada'],
            ['code' => 'GP', 'flag' => 'GP.png', 'name' => 'Guadeloupe'],
            ['code' => 'GU', 'flag' => 'GU.png', 'name' => 'Guam'],
            ['code' => 'GT', 'flag' => 'GT.png', 'name' => 'Guatemala'],
            ['code' => 'GN', 'flag' => 'GN.png', 'name' => 'Guinea'],
            ['code' => 'GW', 'flag' => 'GW.png', 'name' => 'Guinea-Bissau'],
            ['code' => 'GY', 'flag' => 'GY.png', 'name' => 'Guyana'],
            ['code' => 'HT', 'flag' => 'HT.png', 'name' => 'Haiti'],
            ['code' => 'HM', 'flag' => 'HM.png', 'name' => 'Heard and Mc Donald Islands'],
            ['code' => 'HN', 'flag' => 'HN.png', 'name' => 'Honduras'],
            ['code' => 'HK', 'flag' => 'HK.png', 'name' => 'Hong Kong'],
            ['code' => 'HU', 'flag' => 'HU.png', 'name' => 'Hungary'],
            ['code' => 'IS', 'flag' => 'IS.png', 'name' => 'Iceland'],
            ['code' => 'IN', 'flag' => 'IN.png', 'name' => 'India'],
            ['code' => 'ID', 'flag' => 'ID.png', 'name' => 'Indonesia'],
            ['code' => 'IR', 'flag' => 'IR.png', 'name' => 'Iran (Islamic Republic of)'],
            ['code' => 'IQ', 'flag' => 'IQ.png', 'name' => 'Iraq'],
            ['code' => 'IE', 'flag' => 'IE.png', 'name' => 'Ireland'],
            ['code' => 'IL', 'flag' => 'IL.png', 'name' => 'Israel'],
            ['code' => 'IT', 'flag' => 'IT.png', 'name' => 'Italy'],
            ['code' => 'CI', 'flag' => 'CI.png', 'name' => 'Ivory Coast'],
            ['code' => 'JM', 'flag' => 'JM.png', 'name' => 'Jamaica'],
            ['code' => 'JP', 'flag' => 'JP.png', 'name' => 'Japan'],
            ['code' => 'JO', 'flag' => 'JO.png', 'name' => 'Jordan'],
            ['code' => 'KZ', 'flag' => 'KZ.png', 'name' => 'Kazakhstan'],
            ['code' => 'KE', 'flag' => 'KE.png', 'name' => 'Kenya'],
            ['code' => 'KI', 'flag' => 'KI.png', 'name' => 'Kiribati'],
            ['code' => 'KP', 'flag' => 'KP.png', 'name' => 'Korea, Democratic People\'s Republic of'],
            ['code' => 'KR', 'flag' => 'KR.png', 'name' => 'Korea, Republic of'],
            ['code' => 'KW', 'flag' => 'KW.png', 'name' => 'Kuwait'],
            ['code' => 'KG', 'flag' => 'KG.png', 'name' => 'Kyrgyzstan'],
            ['code' => 'LA', 'flag' => 'LA.png', 'name' => 'Lao People\'s Democratic Republic'],
            ['code' => 'LV', 'flag' => 'LV.png', 'name' => 'Latvia'],
            ['code' => 'LB', 'flag' => 'LB.png', 'name' => 'Lebanon'],
            ['code' => 'LS', 'flag' => 'LS.png', 'name' => 'Lesotho'],
            ['code' => 'LR', 'flag' => 'LR.png', 'name' => 'Liberia'],
            ['code' => 'LY', 'flag' => 'LY.png', 'name' => 'Libyan Arab Jamahiriya'],
            ['code' => 'LI', 'flag' => 'LI.png', 'name' => 'Liechtenstein'],
            ['code' => 'LT', 'flag' => 'LT.png', 'name' => 'Lithuania'],
            ['code' => 'LU', 'flag' => 'LU.png', 'name' => 'Luxembourg'],
            ['code' => 'MO', 'flag' => 'MO.png', 'name' => 'Macau'],
            ['code' => 'MK', 'flag' => 'MK.png', 'name' => 'Macedonia'],
            ['code' => 'MG', 'flag' => 'MG.png', 'name' => 'Madagascar'],
            ['code' => 'MW', 'flag' => 'MW.png', 'name' => 'Malawi'],
            ['code' => 'MY', 'flag' => 'MY.png', 'name' => 'Malaysia'],
            ['code' => 'MV', 'flag' => 'MV.png', 'name' => 'Maldives'],
            ['code' => 'ML', 'flag' => 'ML.png', 'name' => 'Mali'],
            ['code' => 'MT', 'flag' => 'MT.png', 'name' => 'Malta'],
            ['code' => 'MH', 'flag' => 'MH.png', 'name' => 'Marshall Islands'],
            ['code' => 'MQ', 'flag' => 'MQ.png', 'name' => 'Martinique'],
            ['code' => 'MR', 'flag' => 'MR.png', 'name' => 'Mauritania'],
            ['code' => 'MU', 'flag' => 'MU.png', 'name' => 'Mauritius'],
            ['code' => 'TY', 'flag' => 'TY.png', 'name' => 'Mayotte'],
            ['code' => 'MX', 'flag' => 'MX.png', 'name' => 'Mexico'],
            ['code' => 'FM', 'flag' => 'FM.png', 'name' => 'Micronesia, Federated States of'],
            ['code' => 'MD', 'flag' => 'MD.png', 'name' => 'Moldova, Republic of'],
            ['code' => 'MC', 'flag' => 'MC.png', 'name' => 'Monaco'],
            ['code' => 'MN', 'flag' => 'MN.png', 'name' => 'Mongolia'],
            ['code' => 'MS', 'flag' => 'MS.png', 'name' => 'Montserrat'],
            ['code' => 'MA', 'flag' => 'MA.png', 'name' => 'Morocco'],
            ['code' => 'MZ', 'flag' => 'MZ.png', 'name' => 'Mozambique'],
            ['code' => 'MM', 'flag' => 'MM.png', 'name' => 'Myanmar'],
            ['code' => 'NA', 'flag' => 'NA.png', 'name' => 'Namibia'],
            ['code' => 'NR', 'flag' => 'NR.png', 'name' => 'Nauru'],
            ['code' => 'NP', 'flag' => 'NP.png', 'name' => 'Nepal'],
            ['code' => 'NL', 'flag' => 'NL.png', 'name' => 'Netherlands'],
            ['code' => 'AN', 'flag' => 'AN.png', 'name' => 'Netherlands Antilles'],
            ['code' => 'NC', 'flag' => 'NC.png', 'name' => 'New Caledonia'],
            ['code' => 'NZ', 'flag' => 'NZ.png', 'name' => 'New Zealand'],
            ['code' => 'NI', 'flag' => 'NI.png', 'name' => 'Nicaragua'],
            ['code' => 'NE', 'flag' => 'NE.png', 'name' => 'Niger'],
            ['code' => 'NG', 'flag' => 'NG.png', 'name' => 'Nigeria'],
            ['code' => 'NU', 'flag' => 'NU.png', 'name' => 'Niue'],
            ['code' => 'NF', 'flag' => 'NF.png', 'name' => 'Norfork Island'],
            ['code' => 'MP', 'flag' => 'MP.png', 'name' => 'Northern Mariana Islands'],
            ['code' => 'NO', 'flag' => 'NO.png', 'name' => 'Norway'],
            ['code' => 'OM', 'flag' => 'OM.png', 'name' => 'Oman'],
            ['code' => 'PK', 'flag' => 'PK.png', 'name' => 'Pakistan'],
            ['code' => 'PW', 'flag' => 'PW.png', 'name' => 'Palau'],
            ['code' => 'PA', 'flag' => 'PA.png', 'name' => 'Panama'],
            ['code' => 'PG', 'flag' => 'PG.png', 'name' => 'Papua New Guinea'],
            ['code' => 'PY', 'flag' => 'PY.png', 'name' => 'Paraguay'],
            ['code' => 'PE', 'flag' => 'PE.png', 'name' => 'Peru'],
            ['code' => 'PH', 'flag' => 'PH.png', 'name' => 'Philippines'],
            ['code' => 'PN', 'flag' => 'PN.png', 'name' => 'Pitcairn'],
            ['code' => 'PL', 'flag' => 'PL.png', 'name' => 'Poland'],
            ['code' => 'PT', 'flag' => 'PT.png', 'name' => 'Portugal'],
            ['code' => 'PR', 'flag' => 'PR.png', 'name' => 'Puerto Rico'],
            ['code' => 'QA', 'flag' => 'QA.png', 'name' => 'Qatar'],
            ['code' => 'SS', 'flag' => 'SS.png', 'name' => 'Republic of South Sudan'],
            ['code' => 'RE', 'flag' => 'RE.png', 'name' => 'Reunion'],
            ['code' => 'RO', 'flag' => 'RO.png', 'name' => 'Romania'],
            ['code' => 'RU', 'flag' => 'RU.png', 'name' => 'Russian Federation'],
            ['code' => 'RW', 'flag' => 'RW.png', 'name' => 'Rwanda'],
            ['code' => 'KN', 'flag' => 'KN.png', 'name' => 'Saint Kitts and Nevis'],
            ['code' => 'LC', 'flag' => 'LC.png', 'name' => 'Saint Lucia'],
            ['code' => 'VC', 'flag' => 'VC.png', 'name' => 'Saint Vincent and the Grenadines'],
            ['code' => 'WS', 'flag' => 'WS.png', 'name' => 'Samoa'],
            ['code' => 'SM', 'flag' => 'SM.png', 'name' => 'San Marino'],
            ['code' => 'ST', 'flag' => 'ST.png', 'name' => 'Sao Tome and Principe'],
            ['code' => 'SA', 'flag' => 'SA.png', 'name' => 'Saudi Arabia'],
            ['code' => 'SN', 'flag' => 'SN.png', 'name' => 'Senegal'],
            ['code' => 'RS', 'flag' => 'RS.png', 'name' => 'Serbia'],
            ['code' => 'SC', 'flag' => 'SC.png', 'name' => 'Seychelles'],
            ['code' => 'SL', 'flag' => 'SL.png', 'name' => 'Sierra Leone'],
            ['code' => 'SG', 'flag' => 'SG.png', 'name' => 'Singapore'],
            ['code' => 'SK', 'flag' => 'SK.png', 'name' => 'Slovakia'],
            ['code' => 'SI', 'flag' => 'SI.png', 'name' => 'Slovenia'],
            ['code' => 'SB', 'flag' => 'SB.png', 'name' => 'Solomon Islands'],
            ['code' => 'SO', 'flag' => 'SO.png', 'name' => 'Somalia'],
            ['code' => 'ZA', 'flag' => 'ZA.png', 'name' => 'South Africa'],
            ['code' => 'GS', 'flag' => 'GS.png', 'name' => 'South Georgia South Sandwich Islands'],
            ['code' => 'ES', 'flag' => 'ES.png', 'name' => 'Spain'],
            ['code' => 'LK', 'flag' => 'LK.png', 'name' => 'Sri Lanka'],
            ['code' => 'SH', 'flag' => 'SH.png', 'name' => 'St. Helena'],
            ['code' => 'PM', 'flag' => 'PM.png', 'name' => 'St. Pierre and Miquelon'],
            ['code' => 'SD', 'flag' => 'SD.png', 'name' => 'Sudan'],
            ['code' => 'SR', 'flag' => 'SR.png', 'name' => 'Suriname'],
            ['code' => 'SJ', 'flag' => 'SJ.png', 'name' => 'Svalbarn and Jan Mayen Islands'],
            ['code' => 'SZ', 'flag' => 'SZ.png', 'name' => 'Swaziland'],
            ['code' => 'SE', 'flag' => 'SE.png', 'name' => 'Sweden'],
            ['code' => 'CH', 'flag' => 'CH.png', 'name' => 'Switzerland'],
            ['code' => 'SY', 'flag' => 'SY.png', 'name' => 'Syrian Arab Republic'],
            ['code' => 'TW', 'flag' => 'TW.png', 'name' => 'Taiwan'],
            ['code' => 'TJ', 'flag' => 'TJ.png', 'name' => 'Tajikistan'],
            ['code' => 'TZ', 'flag' => 'TZ.png', 'name' => 'Tanzania, United Republic of'],
            ['code' => 'TH', 'flag' => 'TH.png', 'name' => 'Thailand'],
            ['code' => 'TG', 'flag' => 'TG.png', 'name' => 'Togo'],
            ['code' => 'TK', 'flag' => 'TK.png', 'name' => 'Tokelau'],
            ['code' => 'TO', 'flag' => 'TO.png', 'name' => 'Tonga'],
            ['code' => 'TT', 'flag' => 'TT.png', 'name' => 'Trinidad and Tobago'],
            ['code' => 'TN', 'flag' => 'TN.png', 'name' => 'Tunisia'],
            ['code' => 'TR', 'flag' => 'TR.png', 'name' => 'Turkey'],
            ['code' => 'TM', 'flag' => 'TM.png', 'name' => 'Turkmenistan'],
            ['code' => 'TC', 'flag' => 'TC.png', 'name' => 'Turks and Caicos Islands'],
            ['code' => 'TV', 'flag' => 'TV.png', 'name' => 'Tuvalu'],
            ['code' => 'UG', 'flag' => 'UG.png', 'name' => 'Uganda'],
            ['code' => 'UA', 'flag' => 'UA.png', 'name' => 'Ukraine'],
            ['code' => 'AE', 'flag' => 'AE.png', 'name' => 'United Arab Emirates'],
            ['code' => 'GB', 'flag' => 'GB.png', 'name' => 'United Kingdom'],
            ['code' => 'UM', 'flag' => 'UM.png', 'name' => 'United States minor outlying islands'],
            ['code' => 'UY', 'flag' => 'UY.png', 'name' => 'Uruguay'],
            ['code' => 'UZ', 'flag' => 'UZ.png', 'name' => 'Uzbekistan'],
            ['code' => 'VU', 'flag' => 'VU.png', 'name' => 'Vanuatu'],
            ['code' => 'VA', 'flag' => 'VA.png', 'name' => 'Vatican City State'],
            ['code' => 'VE', 'flag' => 'VE.png', 'name' => 'Venezuela'],
            ['code' => 'VN', 'flag' => 'VN.png', 'name' => 'Vietnam'],
            ['code' => 'VG', 'flag' => 'VG.png', 'name' => 'Virgin Islands (British)'],
            ['code' => 'VI', 'flag' => 'VI.png', 'name' => 'Virgin Islands (U.S.)'],
            ['code' => 'WF', 'flag' => 'WF.png', 'name' => 'Wallis and Futuna Islands'],
            ['code' => 'EH', 'flag' => 'EH.png', 'name' => 'Western Sahara'],
            ['code' => 'YE', 'flag' => 'YE.png', 'name' => 'Yemen'],
            ['code' => 'YU', 'flag' => 'YU.png', 'name' => 'Yugoslavia'],
            ['code' => 'ZR', 'flag' => 'ZR.png', 'name' => 'Zaire'],
            ['code' => 'ZM', 'flag' => 'ZM.png', 'name' => 'Zambia'],
            ['code' => 'ZW', 'flag' => 'ZW.png', 'name' => 'Zimbabwe'],
        ];

        DB::table('countries')->insert($countries);
    }
}
